/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.eclipse.xtext.idea.lang.XtextLanguage;
import org.jetbrains.annotations.NotNull;

public class XtextSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return XtextLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
