/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.facet

import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage

@State(name = "org.eclipse.xtext.XtextGenerator", storages = #[
		@Storage("XtextGeneratorConfig.xml")])
 class XtextFacetConfiguration extends AbstractFacetConfiguration implements PersistentStateComponent<GeneratorConfigurationState>{

}
