/*
 * generated by Xtext
 */
package org.eclipse.xtext.purexbase.idea.lang.parser.antlr;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

import java.io.InputStream;

public class PureXbaseAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/xtext/purexbase/idea/parser/antlr/internal/PsiInternalPureXbase.tokens");
	}
}
