/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.idea.lang.XtextFileType;
import org.eclipse.xtext.idea.lang.XtextLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class XtextFileImpl extends BaseXtextFile {

	public XtextFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, XtextLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return XtextFileType.INSTANCE;
	}
}
