/*
 * generated by Xtext
 */
package org.eclipse.xtext.purexbase.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.eclipse.xtext.purexbase.idea.lang.PureXbaseLanguage;

public class PureXbaseExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return PureXbaseLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
