/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractXtextCompletionContributor extends TerminalsCompletionContributor {
	public AbstractXtextCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
