/*
 * generated by Xtext
 */
package org.eclipse.xtext.generator.ecore.idea.facet

import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import org.eclipse.xtext.idea.facet.AbstractFacetConfiguration
import org.eclipse.xtext.idea.facet.GeneratorConfigurationState

@State(name = "org.eclipse.xtext.generator.ecore.SuperTestLanguageGenerator", storages = #[
		@Storage("SuperTestLanguageGeneratorConfig.xml")])
 class SuperTestLanguageFacetConfiguration extends AbstractFacetConfiguration implements PersistentStateComponent<GeneratorConfigurationState>{

}
