/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.lang.pom;

import org.eclipse.xtext.idea.lang.XtextLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class XtextPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public XtextPomDeclarationSearcher() {
		super(XtextLanguage.INSTANCE);
	}
}
