/*
 * generated by Xtext
 */
package org.eclipse.xtext.purexbase.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.eclipse.xtext.purexbase.idea.lang.PureXbaseLanguage;

public class PureXbaseFacetType extends AbstractFacetType<PureXbaseFacetConfiguration> {

	public static final FacetTypeId<Facet<PureXbaseFacetConfiguration>> TYPEID = new FacetTypeId<Facet<PureXbaseFacetConfiguration>>("org.eclipse.xtext.purexbase.PureXbase");

	public PureXbaseFacetType() {
		super(TYPEID, "org.eclipse.xtext.purexbase.PureXbase", "PureXbase");
		PureXbaseLanguage.INSTANCE.injectMembers(this);
	}
}
