/*
 * generated by Xtext
 */
package org.eclipse.xtext.purexbase.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class PureXbaseIdeaModule extends AbstractPureXbaseIdeaModule {
}
