/**
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import org.eclipse.xtext.XtextRuntimeModule;
import org.eclipse.xtext.XtextStandaloneSetupGenerated;
import org.eclipse.xtext.idea.XtextIdeaModule;
import org.eclipse.xtext.util.Modules2;

@SuppressWarnings("all")
public class XtextStandaloneSetupIdea extends XtextStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    final XtextRuntimeModule runtimeModule = new XtextRuntimeModule();
    final XtextIdeaModule ideaModule = new XtextIdeaModule();
    final Module mergedModule = Modules2.mixin(runtimeModule, ideaModule);
    return Guice.createInjector(mergedModule);
  }
}
