/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.lang;


public final class XtextLanguage extends AbstractXtextLanguage {

	public static final XtextLanguage INSTANCE = new XtextLanguage();

	private XtextLanguage() {
		super("org.eclipse.xtext.Xtext");
	}

}
