/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class XtextFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(XtextFileType.INSTANCE, AbstractXtextFileType.DEFAULT_EXTENSION);
	}

}
