/*
 * generated by Xtext 2.11
 */
package org.eclipse.xtext.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.lang.XtextLanguage;

public class XtextFacetType extends AbstractFacetType<XtextFacetConfiguration> {

	public static final FacetTypeId<Facet<XtextFacetConfiguration>> TYPEID = new FacetTypeId<Facet<XtextFacetConfiguration>>("org.eclipse.xtext.Xtext");

	public XtextFacetType() {
		super(TYPEID, "org.eclipse.xtext.Xtext", "Xtext");
		XtextLanguage.INSTANCE.injectMembers(this);
	}
}
